### PR TITLE
Myuscis

### PR DESCRIPTION
**Pull request by gboone**
Paging @jpyuda @leahbannon and anyone else involved with this project. Merging this will put the page on Staging, if you :+1: it then we'll roll to production.

### CODE REVIEW

**Comment by leahbannon** [comment]
Sorry, I'm not totally clear on what this does. I see that it adds myuscis to the list on the dashboard homepage (screenshot below), but then what? If I click on the link, I get Not Found (although maybe I have the wrong link?). I would be :-1: to this if we have nothing but the name of the project to add to that list and the "Code" link isn't going to work for anyone.

screen shot 2015-01-29 at 12 42 51 pm

**Comment by gboone** [comment]
This fixes that; makes it look like this but without the empty code section:
screen shot 2015-01-29 at 11 50 55 am

**Comment by jpyuda** [comment]
Can we move "myuscis.html" to "uscis.html"?

**Comment by gboone** [comment]
Done.

On Thu, Jan 29, 2015 at 2:25 PM, John P. Yuda notifications@github.com
wrote:

> Can we move "myuscis.html" to "uscis.html"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/dashboard/pull/183#issuecomment-72087277.

## 

Greg Boone, 18F

**Comment by jpyuda** [comment]
Excellent. I'm merging.

**Comment by gboone** [comment]
@jpyuda take a look at this one, too: https://github.com/18F/data-private/pull/34

**Comment by gboone** [comment]
@USCIS team: I'm aware this is still broken looking on staging. 90% sure it's because the deploy hook went down. I'm working on getting it sorted out now.

**Pull request merged**
