### PR TITLE
Updating FOIA team members.

### LINKED ISSUE #163: FOIA team is not up to date
FOIA team was missing a few names and we had some new additions. 
Here is the list in last name alphabetical order: jackie, shashank, cm, majma, eric, gabriel, jess, victor

### PR DESCRIPTION
**Pull request by jackiekazil**
Fixes #163.

### CODE REVIEW

**Comment by leahbannon** [comment]
Jackie, this needs to match the data on the 18F site. Some of these folks are not on the 18F site, and I haven't verified that the names all match, but I'd appreciate if you would double check that.

**Comment by jackiekazil** [comment]
@leahbannon Ty. Checking now. Can I assign it to you when I am done for checking?

**Comment by jackiekazil** [comment]
@leahbannon -- just clarify to be a part of 18F site, you need to be in this yml yes? 
https://github.com/18F/18f.gsa.gov/blob/staging/_data/team.yml

And what if someone is 'hidden', like myself? That doesn't effect anything on this side does it?

**Comment by jackiekazil** [comment]
@gboone assigning this to you for merging as we talked about today.

**Comment by gboone** [comment]
Even though there are team members listed who aren't on the team.yml: merging.

**Pull request merged**
