### PR TITLE
updated teams FOIA/FEC

### PR DESCRIPTION
**Pull request by rjmajma**
updated these teams. Not sure what "name" Micah will go by. Also used the names that connect to the Hub. Hopefully this all works.

### CODE REVIEW

**Comment by rjmajma** [comment]
Sorry, just saw Jackie's update. Didn't realize she was already on it. 

Made a few changes outside of that. Always happy to just close this one and make changes to Team FEC separately if you'd prefer.

**Comment by gboone** [comment]
@rjmajma there was a merge conflict between yours and Jackie's changes to the "FOIA Modernization" team. The difference was the order of the names and I resolved it by picking the one. I'll need a :+1: or more edits from you in order to merge.

**Comment by rjmajma** [comment]
I need a podcast from you in order to merge.

**Comment by leahbannon** [comment]
I'm closing this because we're no longer pulling data from this file, but from hub data-private.

**Pull request closed without merging**
