### PR TITLE
Update ascii.html

### PR DESCRIPTION
**Pull request by wslack**
adding addl info to ASCII page

### CODE REVIEW

**Comment by gboone** [comment]
Think we should update the email address, too?

**Comment by wslack** [comment]
Would defer to TT; I didn't see that address anywhere on the page and I don't think we're using it anymore....maybe?

**Comment by gboone** [comment]
@jamiealbrecht should we point people to page.18f.gov/joining-18f instead of asking them to email us?

**Comment by mbland** [comment]
Any reason not to merge this?

**Comment by wslack** [comment]
I would explicitly refer to @jamiealbrecht and TT before merging anything.

**Comment by jamiealbrecht** [comment]
Direct folks to join18f@gsa.gov please.

**Comment by wslack** [comment]
As long as Travis is happy, I think that edit is aligned with Jamie's directions.

**Pull request merged**
