### PR TITLE
Adding support for subprojects and repo links.

### PR DESCRIPTION
**Pull request by DavidEBest**
Subprojects:
Subprojects are designated with a `parent` tag in the about.yml. The dashboard plugin will pull them into the parent repo in a children key.

Repo Links:
Repo Links are designated by setting the link `category` to `repo`. The link text should be either a full url to a github repo (https://github.com/18F/federalist) or a org/name slug (18F/federalist). Repo links will not show up in the related links, but will be listed in the `code` section of the site. A repo link has precedence over a subproject; a subproject will not be listed as such if it is also included as a repo link.

Layout/Include Changes:
- The `code` and `links` sections were pulled into seperate includes.
- A new style was added to for `h2` project name headers.
- The code to display a repo's license information was simplified.
- The look does not change for projects without child projects.

Concerns:
- The repo links functionality and subprojects won't 'just work' with the ongoing `preview` functionality that is being developed, since both of those pieces are done in the dashboard plugin.
- Not thrilled with the layout for multiprojects, I'd love to get some suggestions.

Multi-project layout, sporting some dummy data:
screenshot 2015-12-18 10 36 07

### CODE REVIEW

**Comment by gboone** [comment]
Thoughts on your concerns:

> The repo links functionality and subprojects won't 'just work' with the ongoing preview functionality that is being developed, since both of those pieces are done in the dashboard plugin.

Curious to hear @jeremiak's thoughts on this but I'm feeling like building that feature into the preview would be more work than it's worth. A simple way would be to define the relationship in both the parent and child about.yml files but that sort of defeats the data design decision behind the child about.yml file.

> Not thrilled with the layout for multiprojects, I'd love to get some suggestions.

I'm OK with it as an MVP. I think eventually we're going to rethink the entire layout anyway. Getting the data we want on the page first is a big step forward. I could see floating them side-by-side, seems like there's a lot of unused whitespace on the right side of the page.

**Comment by DavidEBest** [comment]
@gboone Adding support for repo links to preview would likely be pretty easy. Not sure if it'd be worth the effort, though. Subprojects could be rather complicated (the child declares the relationship) and almost certainly not worth the effort.

We might want to hold off preview support for 'advanced' projects until this functionality gets pushed back into the team api.

**Comment by DavidEBest** [comment]
Related to #305.

**Comment by DavidEBest** [comment]
@ultrasaurus, @gboone What needs to happen here to get this merged?

**Pull request merged**
