### PR TITLE
Update to README based on new about.yml process

### PR DESCRIPTION
**Pull request by leahbannon**

### CODE REVIEW

**Comment by wslack** [comment]
LGTM (but I am not the expert here)

**Comment by leahbannon** [comment]
Hold off on merging this -- I'd like to figure out and explain a few details about data fields blog, contact, and teammate.

**Comment by leahbannon** [comment]
Actually, not sure I'll figure out contact and blog soon. Plz merge.

**Comment by gboone** [comment]
I'm going to push up a little more based on some changes I made this morning. Thanks for getting this started, @leahbannon.

**Comment by NoahKunin** [comment]
Conflicts :warning: cc @leahbannon @gboone

**Comment by gboone** [comment]
OK, I think the merge conflicts are resolved now. This should be good to merge. @18F/dashboard

**Pull request merged**
