### PR TITLE
Revised project info

### PR DESCRIPTION
**Pull request by seanherron**

### CODE REVIEW

**Comment by gboone** [comment]
Sean, can you make sure you've fully merged from the `gh-pages` branch? It looks like you're trying to remove all the FEC projects.

**Comment by leahbannon** [comment]
Also, I believe the people you added have not added themselves to the site and have not responded to my offer to add them.

**Comment by leahbannon** [comment]
For impact, some possible edits? "7,000 Peace Corps Volunteers in the field, hundreds of thousands of prospective and returned Volunteers, and their friends and families."

**Comment by seanherron** [comment]
@gbinal yes - That repo is where the project is. When you make multiple repos the current site just combines them all in to a nonworking URL, so I thought there should only be one repo per project?

@leahbannon Okay, those edits sound good. You can merge in with that if you would like.

**Comment by gboone** [comment]
I'm not sure what you mean, @seanherron (assuming you meant me). All the repos listed here currently work: http://18f.github.io/dashboard/project/openfec/

**Comment by gboone** [comment]
Never mind, you mean on the root page. Thanks for catching that bug!

**Comment by seanherron** [comment]
Yup - didn't realize there were subpages too.

**Pull request merged**
