### PR TITLE
midas -> alpha

### PR DESCRIPTION
**Pull request by ultrasaurus**
also we have partners, not clients
little bit of word-smithing

### CODE REVIEW

**Comment by leahbannon** [comment]
Thanks for the updates, Sarah. I think GSA as paying client was a milestone that you or Joe added. Are you sure you want to remove mention of GSA? Also, can we use a different word than "real-world," or just delete it? I'm not sure what it conveys, since everything we do is in the real world. If you're trying to convey that it's on the live, public web, I think you did that with the public link.

**Comment by leahbannon** [comment]
Oh, also, I think Travis might be failing because of the extra quotation mark added in line 287

**Comment by ultrasaurus** [comment]
Oh, yeah.  I forgot we separated into two milestones.  Want to re-word as partner, not client.
I'll also fix the extra quotation mark -- sorry about that!

**Comment by ultrasaurus** [comment]
on the "real-world" wording.... I'm trying to differentiate QA testing, where people put in fake data and kick-the-tires (which was happening before with a test instance) and launching for active use.  How about:  

```
September 2014: "18F launches http://midas.18f.us for use by early adopters"
```

**Comment by leahbannon** [comment]
That's great! Just make sure quotation mark is outside of September, not in front of 18F:

"September 2014: 18F launches http://midas.18f.us for use by early adopters"

**Comment by ultrasaurus** [comment]
Travis passed, so it looks like I got my quotation marks correct this time.  Please take a look when you get a chance :)

**Pull request merged**
