### PR TITLE
Update head.html

### PR DESCRIPTION
**Pull request by abosio**
This patch addresses issues #124 and #178. (The loop creates some unsightly white space in the generated source but it looks like that is a common problem with Liquid.) I'm a little early for Code Across America and this is my first time, so I'd appreciate any feedback for improvement. (Apologies for the misfire on the earlier cancelled pull request. I noticed a problem right after submitting it.)

### CODE REVIEW

**Comment by abosio** [comment]
I've been thinking about how my solution creates a loop in the head - modeled after what I saw for the page content - which I believe will add a performance hit to the rendering of every page during build, even the pages which are not projects. This is somewhat mitigated by the fact that it will not effect the end user like it would in a one-the-fly page render setup, but it is still less than ideal. Especially since it will be repeated further down on all the project pages. So it would be better to do it once in the head, set a variable and use it in both places, but is there any way to avoid the loop on pages which are not projects?

**Comment by gboone** [comment]
Hi @abosio thanks for the contribution and sorry it took the weekend for me to get back to you. To your question, I think there might be a way to tell if we're in a project context without looping at all. Every project's page has the layout "project" so I think we could check for `{{ page.layout }}` to equal `project` before the loop and assign `isproject == true` at that point.

(Also, a GitHub tip: you could have left your original pull request open and continued pushing commits into that same branch. So if you continue making changes to this pull request, make sure to commit them to the branch `patch-1` and your pull request should update automatically.)

**Comment by abosio** [comment]
Thank you. With that knowledge I will improve on this and comment when ready.

**Comment by abosio** [comment]
`page.layout` returns `bare`, not `project`. I guess that is because `project.html` has `layout: bare` but I'm not sure why the `layout: project` in `pages/projetcs/[project-name].html` does not override.

**Comment by abosio** [comment]
I have not been able to find a way to improve on the current commit. It still fixes #124 and #178.

**Comment by gboone** [comment]
Hey @abosio, I'm reviewing this again now, but sorry it's taken me a couple days to get back to you. Thanks for the submission.

**Pull request merged**
