### PR TITLE
[WIP] team-api-update.js webhook listener

### PR DESCRIPTION
**Pull request by mbland**
Hookshot listener for listening for automated Team API updates and creating pull requests against the staging branch.

Have it running manually right now; about to open a PR to add an [`.about.yml` file](https://github.com/18F/about_yml) to the Dashboard, to see if the end-to-end system is working as advertised.

cc: @gboone

### CODE REVIEW

**Comment by gboone** [comment]
Cool. Thanks for the leg work, @mbland. Going to merge this after Federalist gets it's `about` file in place and then we should see the new project right away. Might also throw a test in to make sure the number of pages generated matches the number of projects in the generated data file.

**Comment by mbland** [comment]
So I managed to run this manually and verify the `.about.yml` -> `team-api.18f.gov` -> Dashboard rebuild webhook flow. Pushed commits with the working code. All's that left is:
- What's the deployment strategy? Another `fabfile.py` entry?
- Need to check in the update to the 18f site nginx config (the 18f.gsa.gov/dashboard/team-api-update entry that I tweaked in prod)
- Right now it's configured to only rebuild staging. It may be prudent to merge this version, then issue a new PR that can rebuild multiple `repoDir`s.

**Comment by mbland** [comment]
Also: https://team-api.18f.gov/public/api/projects/dashboard/

**Comment by mbland** [comment]
BTW, this should go in and get deployed _before_ 18F/federalist#142 to see the flow actually working.

**Comment by gboone** [comment]
Alright, we'll merge this and #246 now and then keep an eye out for 18F/federalist#142

**Comment by mbland** [comment]
FWIW, I launched the server by hand via:

``` shell
$ forever start -l $HOME/team-api-update.log -a staging/dashboard/deploy/team-api-update.js
```

And you can already see [the Dashboard entry on the Dashboard staging site](https://staging.18f.us/dashboard/project/dashboard/). Which is to say, if you want to see `.about.yml` updates live in staging, you can.

**Pull request merged**
