### PR TITLE
Update import-public.rb to import Hub API JSON

### PR DESCRIPTION
**Pull request by mbland**
Replaces the need for the `_data/private` git submodule. Depends on 18F/hub#182 going in first. When that's done, I'll add the imported `projects.json` file.

cc: @gboone

### CODE REVIEW

**Comment by gboone** [comment]
Looks good, @mbland I'm going to pull the branch down and run the script to generate the data file to make sure it all comes out correctly.

**Comment by gboone** [comment]
This will (if merged) render #193 obsolete, right?

**Comment by mbland** [comment]
Yes, it will.

**Comment by mbland** [comment]
Now that 18F/hub#182 is in, waiting for a public Hub deployment to expose the new API before following through on this PR.

**Comment by mbland** [comment]
With public Hub push 18F/hub#189 now live, I've imported `_data/projects.json` and added it to this here PR. Looks great on my machine!

**Comment by gboone** [comment]
There's one change I need to push before we merge: rename the page for the project formerly known as mirage to discovery.

**Comment by mbland** [comment]
Y'know, it shows up alright in the API already: https://18f.gsa.gov/hub/api/projects/

**Comment by gboone** [comment]
Yeah, but the file `page/project/discovery.html` needs to be there or `.../dashboard/discovery/` (as linked on the landing page) will 404

**Comment by gboone** [comment]
see: 0613f22, I think this is good now

**Comment by mbland** [comment]
Ohh... Sorry, I thought you meant the YAML file, not the dashboard file. Nevermind. :-P Guess you can pull when ready!

**Pull request merged**
