### PR TITLE
Integrate with https://team-api.18f.gov/public/api/

### PR DESCRIPTION
**Pull request by mbland**
Depends on #238. After this, I'll update the pages to dynamically update their data by fetching from the Team API.

cc: @gboone

### CODE REVIEW

**Comment by mbland** [comment]
OK, this is almost good to go. A few notes:
- I imported the latest Team API data into `_data/projects.json`, which now accounts for the bulk of the diff. If you'd rather, I can remove this commit to make the PR less noisy.
- The changes to `_data/import-public.rb` and `_plugins/dashboard.rb` are the substantial parts.
- Fetching from the Team API directly is still disabled for now, given that `team_api:` is prefixed with an underscore in `_config.yml`. I can remove this underscore and go live with it if you want; and then we can go about setting up a webhook to regenerate the Dashboard whenever the Team API is updated.

**Comment by mbland** [comment]
Ping... Any chance of a merge soon? Again, happy to split out the data updates into a new PR if need be.

cc: @jeanninehunter

**Comment by mbland** [comment]
Thanks, @gboone! Any word on when we might cut a new public Dashboard?

**Comment by gboone** [comment]
It should cut itself automatically once we merge a PR from `staging` to `production.` Deployments go through webhooks just like 18F/18f.gsa.gov

**Comment by mbland** [comment]
Yes, just wondering when that might be. :-)

**Comment by gboone** [comment]
see #242

**Pull request merged**
