### PR TITLE
Initial commit of contact info in footer

### PR DESCRIPTION
**Pull request by meiqimichelle**
As per #129 .

screenshot 2014-10-24 10 51 15

### CODE REVIEW

**Comment by konklone** [comment]
"Curious about getting dashboard for your agency?" sounds like bad grammar to those who don't immediately think of "dashboard" as the product name. Maybe "Curious about getting a dashboard like this for your agency?"

**Comment by meiqimichelle** [comment]
+1 @konklone -- I like the language suggestion. Will that work for you, @leahbannon ?

**Comment by meiqimichelle** [comment]
3c22f29 adds the footer to project pages, and also adds an 'alpha' bug as per #132 (sorry, should have been separate PR/commit)

Looks like this:
screenshot 2014-10-24 12 05 02

be470cf adds the foot to stage pages.

**Comment by leahbannon** [comment]
language change and alpha message look good to me

**Pull request merged**
