### PR TITLE
Dataediting

### PR DESCRIPTION
**Pull request by leahbannon**
I might keep adding edits throughout the day, so hold off on merging

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@leahbannon perhaps the Travis fail is the backslash in the stack listing?? Would recommend JavaScript being listed separately from Node anyways so we could evening tag and search based on stack if we wanted to. Thoughts?

**Comment by gboone** [comment]
You can ignore the travis failure for now. It's a problem with the travis.yml file.

**Comment by meiqimichelle** [comment]
@leah should we delete this PR?

**Comment by leahbannon** [comment]
Yes.

**Pull request closed without merging**
