### PR TITLE
Capybara integration

### PR DESCRIPTION
**Pull request by gboone**
About time I figured this out. Frontend tests for the Dashboard. Addresses #217

### CODE REVIEW

**Comment by gboone** [comment]
OK! This thing should start passing as soon as @coreycaitlin is added to the Team API. She has a markdown file in 18F/data-private so it should be a matter of rebuilding the API.

**Comment by DavidEBest** [comment]
@gboone I corrected the merge conflicts & simplified a syntax in the travis.yml file a bit.

**Comment by gboone** [comment]
Cool. My gut says these tests will never fail given the changes we introduced in #309 but I think we'll end up writing capybara tests in the future so we might as well merge this now regardless.

**Comment by DavidEBest** [comment]
@gboone I might have dropped the ball on this one... want me to merge?

**Comment by gboone** [comment]
Sure! I was just thinking about some other tests we could write.

**Pull request merged**
